// generates app_html.h — the editor bundled into the Windows launcher
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const src = process.argv[2] || path.join(root, 'editor/dist/montaj-pro.html');
const out = process.argv[3] || path.join(root, 'tools/win/app_html.h');
const buf = fs.readFileSync(src);
let s = '/* generated by tools/win/embed.mjs — do not edit */\nstatic const unsigned char APP_HTML[] = {\n';
for (let i = 0; i < buf.length; i++) {
  s += buf[i] + ',';
  if (i % 24 === 23) s += '\n';
}
s += '0};\nstatic const unsigned long APP_HTML_LEN = ' + buf.length + 'UL;\n';
fs.writeFileSync(out, s);
console.log('embedded', (buf.length / 1024).toFixed(0) + ' KB ->', path.relative(root, out));
