/* Montaj Pro — Windows launcher
 *
 * A tiny native .exe that serves the bundled web app over http://127.0.0.1:<random>
 * and opens it in an app-mode window (Edge if present, otherwise the default browser).
 * Why a server and not file://? Because http://localhost is a secure origin: storage,
 * workers and WebCodecs all behave exactly like they do on the web, and downloads
 * land in the normal Downloads folder.
 *
 * Build:  zig cc -target x86_64-windows-gnu -O2 -mwindows launcher.c -o MontajPro.exe -lws2_32
 * (app_html.h is generated by tools/win/embed.mjs)
 */
#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0x0601
#endif
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <shlobj.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "app_html.h"

#define PORT_TRIES 40
#define IDLE_EXIT_MS 180000     /* exit if the browser never talks to us again */

static volatile LONG g_lastPing = 0;
static HANDLE g_stop = NULL;

static void logline(const char *msg) {
    char path[MAX_PATH];
    if (GetModuleFileNameA(NULL, path, MAX_PATH)) {
        char *dot = strrchr(path, '.');
        if (dot) strcpy(dot, ".log");
        FILE *f = fopen(path, "a");
        if (f) { fprintf(f, "%s\n", msg); fclose(f); }
    }
}

static void send_all(SOCKET s, const char *buf, size_t len) {
    size_t sent = 0;
    while (sent < len) {
        int n = send(s, buf + sent, (int)(len - sent), 0);
        if (n <= 0) return;
        sent += (size_t)n;
    }
}

static void http_response(SOCKET s, int code, const char *ctype, const unsigned char *body, size_t len, int extra_headers) {
    char head[512];
    const char *reason = code == 200 ? "OK" : code == 404 ? "Not Found" : "Error";
    int n = snprintf(head, sizeof(head),
        "HTTP/1.1 %d %s\r\nContent-Type: %s\r\nContent-Length: %llu\r\n"
        "Cache-Control: no-store\r\nConnection: close\r\n%s\r\n",
        code, reason, ctype, (unsigned long long)len,
        extra_headers ? "Access-Control-Allow-Origin: *\r\n" : "");
    send_all(s, head, (size_t)n);
    if (body && len) send_all(s, (const char *)body, len);
}

static DWORD WINAPI client_thread(LPVOID param) {
    SOCKET s = (SOCKET)(size_t)param;
    char req[2048];
    int got = recv(s, req, sizeof(req) - 1, 0);
    if (got <= 0) { closesocket(s); return 0; }
    req[got] = 0;
    if (strncmp(req, "GET /", 5) == 0) {
        if (strncmp(req, "GET /ping", 9) == 0) {
            InterlockedExchange(&g_lastPing, (LONG)GetTickCount());
            http_response(s, 200, "text/plain", (const unsigned char *)"ok", 2, 1);
        } else if (strncmp(req, "GET /favicon.ico", 16) == 0) {
            http_response(s, 404, "text/plain", (const unsigned char *)"", 0, 0);
        } else {
            http_response(s, 200, "text/html; charset=utf-8", APP_HTML, APP_HTML_LEN, 0);
        }
    } else {
        http_response(s, 404, "text/plain", (const unsigned char *)"no", 2, 0);
    }
    shutdown(s, SD_SEND);
    closesocket(s);
    return 0;
}

static DWORD WINAPI server_thread(LPVOID param) {
    SOCKET srv = (SOCKET)(size_t)param;
    while (WaitForSingleObject(g_stop, 0) == WAIT_TIMEOUT) {
        fd_set fds;
        FD_ZERO(&fds);
        FD_SET(srv, &fds);
        struct timeval tv = { 0, 250000 };
        if (select(0, &fds, NULL, NULL, &tv) <= 0) continue;
        SOCKET c = accept(srv, NULL, NULL);
        if (c == INVALID_SOCKET) continue;
        HANDLE t = CreateThread(NULL, 0, client_thread, (LPVOID)(size_t)c, 0, NULL);
        if (t) CloseHandle(t); else closesocket(c);
    }
    return 0;
}

static int file_exists(const char *p) {
    DWORD a = GetFileAttributesA(p);
    return a != INVALID_FILE_ATTRIBUTES && !(a & FILE_ATTRIBUTE_DIRECTORY);
}

static int find_edge(char *out, size_t outsz) {
    const char *cands[] = {
        "%ProgramFiles(x86)%\\Microsoft\\Edge\\Application\\msedge.exe",
        "%ProgramFiles%\\Microsoft\\Edge\\Application\\msedge.exe",
        "%LOCALAPPDATA%\\Microsoft\\Edge\\Application\\msedge.exe",
    };
    for (int i = 0; i < 3; i++) {
        char expanded[MAX_PATH];
        DWORD n = ExpandEnvironmentStringsA(cands[i], expanded, MAX_PATH);
        if (n && n < MAX_PATH && file_exists(expanded)) {
            strncpy(out, expanded, outsz - 1);
            out[outsz - 1] = 0;
            return 1;
        }
    }
    /* last chance: registry free "where.exe" search */
    if (SearchPathA(NULL, "msedge.exe", NULL, (DWORD)outsz, out, NULL)) return 1;
    return 0;
}

static int montaj_main(HINSTANCE hInst, HINSTANCE hPrev, LPSTR cmdLine, int nShow) {
    (void)hInst; (void)hPrev; (void)cmdLine; (void)nShow;
    g_stop = CreateEvent(NULL, TRUE, FALSE, NULL);
    InterlockedExchange(&g_lastPing, (LONG)GetTickCount());

    WSADATA wsa;
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) {
        MessageBoxA(NULL, "Winsock init failed.", "Montaj Pro", MB_ICONERROR);
        return 1;
    }
    SOCKET srv = INVALID_SOCKET;
    int port = 0;
    for (int i = 0; i < PORT_TRIES; i++) {
        srv = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
        if (srv == INVALID_SOCKET) break;
        struct sockaddr_in addr;
        memset(&addr, 0, sizeof(addr));
        addr.sin_family = AF_INET;
        addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
        addr.sin_port = htons((u_short)(38000 + (GetTickCount() % 5000) + i));
        if (bind(srv, (struct sockaddr *)&addr, sizeof(addr)) == 0) { port = ntohs(addr.sin_port); break; }
        closesocket(srv);
        srv = INVALID_SOCKET;
    }
    if (srv == INVALID_SOCKET || listen(srv, 16) != 0) {
        MessageBoxA(NULL, "Could not start the local server.", "Montaj Pro", MB_ICONERROR);
        return 1;
    }

    HANDLE sth = CreateThread(NULL, 0, server_thread, (LPVOID)(size_t)srv, 0, NULL);
    (void)sth;

    char url[256];
    snprintf(url, sizeof(url), "http://127.0.0.1:%d/index.html", port);

    char edge[MAX_PATH];
    char workdir[MAX_PATH];
    GetModuleFileNameA(NULL, workdir, MAX_PATH);
    char *slash = strrchr(workdir, '\\');
    if (slash) *slash = 0;

    char profile[MAX_PATH];
    snprintf(profile, sizeof(profile), "%s\\MontajPro-Profile", workdir);

    int launched = 0;
    if (find_edge(edge, sizeof(edge))) {
        char args[1600];
        snprintf(args, sizeof(args),
                 "\"%s\" --app=%s --user-data-dir=\"%s\" --no-first-run --no-default-browser-check "
                 "--disable-features=Translate --window-size=1280,820",
                 edge, url, profile);
        STARTUPINFOA si;
        PROCESS_INFORMATION pi;
        memset(&si, 0, sizeof(si));
        si.cb = sizeof(si);
        memset(&pi, 0, sizeof(pi));
        if (CreateProcessA(NULL, args, NULL, NULL, FALSE, 0, NULL, workdir, &si, &pi)) {
            launched = 1;
            CloseHandle(pi.hThread);
            CloseHandle(pi.hProcess);
        } else {
            logline("CreateProcess(edge) failed");
        }
    }
    if (!launched) {
        HINSTANCE r = ShellExecuteA(NULL, "open", url, NULL, NULL, SW_SHOWNORMAL);
        if ((INT_PTR)r <= 32) {
            MessageBoxA(NULL, "Could not open a browser window.\nThe app link is shown in the next dialog.",
                        "Montaj Pro", MB_ICONWARNING);
            MessageBoxA(NULL, url, "Montaj Pro — open this link in your browser", MB_OK);
        }
    }

    /* keep serving while the browser page is alive (it pings us) */
    for (;;) {
        Sleep(500);
        DWORD now = GetTickCount();
        LONG last = InterlockedCompareExchange(&g_lastPing, 0, 0);
        if (last && (DWORD)(now - (DWORD)last) > IDLE_EXIT_MS) break;
    }
    SetEvent(g_stop);
    Sleep(200);
    closesocket(srv);
    WSACleanup();
    return 0;
}

/* two entry points so the mingw CRT finds whichever one its startup object expects */
int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrev, LPSTR cmdLine, int nShow) {
    return montaj_main(hInst, hPrev, cmdLine, nShow);
}

int main(void) {
    return montaj_main(NULL, NULL, NULL, SW_SHOWNORMAL);
}
