// NovaForge Engine - physics world
//
// Real rigid body simulation on top of Bullet3 (vendored in third_party/).
// The physics world is *scene driven*: `syncScene()` mirrors the scene's
// Collider/RigidBody/Character/NPC components into Bullet bodies, `step()`
// simulates them and `writebackTransforms()` pushes the results back into the
// scene transforms. Nothing here is a stub: if a body does not move, it is
// because the simulation says so.
//
// Supported in V1
//   * static / dynamic / kinematic rigid bodies (box, sphere, capsule,
//     cylinder, convex hull, static triangle mesh)
//   * trigger volumes (overlap enter / exit events)
//   * kinematic character controller (walk, run, jump, step up)
//   * raycasts and sphere overlap queries
//   * debug wireframes for the viewport
#pragma once
#include "core/math.h"
#include "scene/scene.h"

#include <functional>
#include <memory>
#include <string>
#include <vector>

namespace nf {

class Mesh;

struct PhysicsSettings {
    Vec3 gravity{0.0f, -9.81f, 0.0f};
    float fixedTimestep = 1.0f / 60.0f;
    int maxSubSteps = 4;
    bool enableCcd = false;
    float sleepLinearThreshold = 0.08f;
    float sleepAngularThreshold = 0.08f;
    std::string stats() const;
};

enum class PhysicsBodyKind { None = 0, Static, Dynamic, Kinematic, Trigger, Character };

const char* toString(PhysicsBodyKind k);

struct RaycastHit {
    bool hit = false;
    EntityId entity = kInvalidEntity;
    Vec3 point{0, 0, 0};
    Vec3 normal{0, 1, 0};
    float distance = 0.0f;
};

struct PhysicsEvent {
    enum class Type { TriggerEnter = 0, TriggerExit, CharacterLanded, CharacterLeftGround };
    Type type = Type::TriggerEnter;
    EntityId a = kInvalidEntity;   // the trigger / character
    EntityId b = kInvalidEntity;   // the other entity (kInvalidEntity when the ground)
    float value = 0.0f;            // impact speed for landings
};

struct PhysicsDebugLine {
    Vec3 a, b;
    Vec3 color{0.15f, 0.9f, 0.35f};
};

// Resolves a mesh asset for ColliderShape::Mesh colliders. The engine wires
// this up to the AssetLibrary; tests can pass a small stand-in.
using PhysicsMeshProvider = std::function<const Mesh*(const std::string& modelPath)>;

class PhysicsWorld {
public:
    explicit PhysicsWorld(const PhysicsSettings& settings = PhysicsSettings());
    ~PhysicsWorld();
    PhysicsWorld(const PhysicsWorld&) = delete;
    PhysicsWorld& operator=(const PhysicsWorld&) = delete;

    void setSettings(const PhysicsSettings& s);
    const PhysicsSettings& settings() const;

    void setMeshProvider(PhysicsMeshProvider provider);
    // Clears and rebuilds everything on the next syncScene() call.
    void clear();

    // ---------------------------------------------------------------- scene
    // Mirrors scene components into Bullet bodies. Safe to call every frame:
    // only entities whose collider signature changed are rebuilt.
    void syncScene(Scene& scene);
    // Advances the simulation by `dt` seconds (fixed step accumulator).
    void step(float dt);
    // Copies body transforms back into the scene (dynamic bodies only).
    void writebackTransforms(Scene& scene);
    // Convenience for the runtime/editor: sync, step, writeback.
    void simulate(Scene& scene, float dt);

    // ------------------------------------------------------------ character
    // Requests a horizontal displacement (world space, metres) for the next
    // step. Gravity and step-up are handled by the character controller.
    void moveCharacter(EntityId entity, const Vec3& displacement);
    void jumpCharacter(EntityId entity, float jumpSpeed);
    void teleportCharacter(Scene& scene, EntityId entity, const Vec3& worldPosition);
    bool isGrounded(EntityId entity) const;
    Vec3 characterVelocity(EntityId entity) const;
    bool hasCharacter(EntityId entity) const;

    // --------------------------------------------------------------- queries
    bool raycast(const Vec3& from, const Vec3& dir, float maxDistance, RaycastHit& out,
                 EntityId ignore = kInvalidEntity) const;
    std::vector<EntityId> overlapSphere(const Vec3& center, float radius,
                                        bool includeTriggers = false) const;

    // ---------------------------------------------------------------- events
    // Events produced since the last drain. Trigger events are generated by
    // diffing overlapping pairs, so they are exact, not sampled.
    std::vector<PhysicsEvent> drainEvents();

    // ----------------------------------------------------------------- debug
    void setDebugDrawEnabled(bool enabled);
    bool debugDrawEnabled() const;
    // Wireframes for the viewport. When `onlyDebugDraw` is true only colliders
    // with ColliderComponent::debugDraw set are emitted.
    void collectDebugLines(std::vector<PhysicsDebugLine>& out, bool onlyDebugDraw) const;

    // ------------------------------------------------------------------ info
    int bodyCount() const;
    int characterCount() const;
    PhysicsBodyKind bodyKind(EntityId entity) const;
    // Number of fixed steps performed since the last reset (diagnostics).
    int stepCount() const;

private:
    struct Impl;
    std::unique_ptr<Impl> impl_;
};

}  // namespace nf
