; ============================================================================
;  GameProject - DefaultEditor.ini
; ============================================================================

[/Script/UnrealEd.UnrealEdOptions]
UsingXGE=False
bExpandCustomClassPickerClassList=True

[/Script/AdvancedPreviewScene.SharedProfiles]

[/Script/UnrealEd.EditorExperimentalSettings]
bWorldBrowser=False

[EditorStartup]
bShowUnrealEditorStartupWindow=False

[AssetEditorSubsystem]
CleanShutdown=True

[/Script/UnrealEd.EditorLoadingSavingSettings]
bSCCAutoAddNewFiles=True
bAutomaticallyCheckoutOnAssetModification=False
bForceCompilationAtStartup=False
bRestoreOpenAssetTabsOnRestart=False
bMonitorContentDirectories=True
AutoReimportDirectorySettings=(SourceDirectory="/Game/",MountPoint="",Wildcards=())
bAutoCreateAssets=True
bDeleteSourceFilesWithAssets=False

[/Script/PythonScriptPlugin.PythonScriptPluginSettings]
bIsolateInterpreterEnvironment=True
bDeveloperMode=True
bRemoteExecution=False
+StartupScripts=
