; ============================================================================
;  GameProject - DefaultEditorPerProjectUserSettings.ini
;  Per-user editor state that we *do* want to version (map/PIE conveniences).
; ============================================================================

[/Script/UnrealEd.LevelEditorPlaySettings]
LastExecutedPlayModeType=PlayMode_InViewPort
CenterNewWindows=False
NewWindowWidth=1600
NewWindowHeight=900
LastSize=(X=0,Y=0)
GameGetsMouseControl=False
MouseControlLabelPosition=LabelAnchorMode_TopLeft
bLaunchSeparateServer=False
PlayNumberOfClients=1
PlayNetMode=PIE_Standalone

[ContentBrowser]
ContentBrowserTab1.SelectedPaths=/Game
ContentBrowserTab1.FavoritesAreaExpanded=False
ContentBrowserTab1.PathBarVisible=True
