import { NextRequest } from 'next/server';
import { z } from 'zod';
import { handler, ok, fail, parseBody, unauthorized } from '@/lib/api';
import { getCurrentUser } from '@/lib/auth';
import { configuredImageProvider, generateImage, UnsupportedProviderError } from '@/lib/ai/providers';
import { generateVariations } from '@/engine/ai-art';
import { usage, users } from '@/lib/repo';

export const runtime = 'nodejs';

const schema = z.object({
  prompt: z.string().min(1).max(2000),
  size: z.enum(['1024x1024', '1536x1024', '1024x1536', '1792x1024', '1024x1792']).default('1024x1024'),
  n: z.number().int().min(1).max(4).default(2),
  style: z.string().max(40).optional(),
  negativePrompt: z.string().max(1000).optional(),
});

export const POST = handler(async (req: NextRequest) => {
  const user = await getCurrentUser();
  if (!user) return unauthorized();

  const record = users.byId(user.id);
  if (record && record.aiCredits <= 0) return fail('AI credits exhausted for this period', 402, 'NO_CREDITS');

  const body = await parseBody(req, schema);
  const [w, h] = (body.size ?? '1024x1024').split('x').map(Number) as [number, number];
  const provider = configuredImageProvider();

  if (provider !== 'local') {
    try {
      const result = await generateImage({
        prompt: body.prompt,
        size: body.size as '1024x1024',
        n: body.n,
        negative: body.negativePrompt,
      });
      usage.record(user.id, 'AI_IMAGE', body.n, { provider: result.provider, prompt: body.prompt.slice(0, 120) });
      return ok({
        images: result.images,
        provider: result.provider,
        model: result.model,
        offline: false,
      });
    } catch (err) {
      if (!(err instanceof UnsupportedProviderError)) {
        console.error('[ai/image] provider failed, falling back to local engine:', err);
      }
    }
  }

  // Offline / fallback path: the deterministic vector art engine.
  const images = generateVariations(body.prompt, body.n, {
    width: Math.min(w, 1024),
    height: Math.min(h, 1024),
    style: (body.style as 'abstract') ?? 'auto',
  }).map((dataUrl) => ({ dataUrl, mime: 'image/svg+xml' }));

  usage.record(user.id, 'AI_IMAGE', body.n, { provider: 'local', prompt: body.prompt.slice(0, 120) });
  return ok({
    images,
    provider: 'local',
    model: 'prism-procedural-1',
    offline: true,
    note: 'Generated by the built-in Prism art engine. Add an image provider key for photorealistic models.',
  });
});
