package com.neurio.langame.common;

import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.MessageDigest;
import java.security.SecureRandom;

import javax.crypto.Mac;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;

/**
 * Local session authentication for the LAN stream.
 *
 * <p>There is no cloud service and no account: the host shows a temporary
 * 6-digit pairing code on screen, the client types it, and both sides derive the
 * same key with PBKDF2-HMAC-SHA256 over the code, the host salt and both nonces.
 * The derived key authenticates every subsequent control frame (HMAC-SHA256 with
 * a monotonically increasing counter and a timestamp to make replay useless) and
 * seeds the session tag stamped into every video/audio/input datagram so that a
 * stray or forged packet from another device on the Wi-Fi is discarded.</p>
 *
 * <p>Threat model: a shared home Wi-Fi with a nosy neighbour. This is not a
 * substitute for a VPN, and it is not meant to cross the internet — the streams
 * are only ever bound to local addresses (see {@code SessionManager}).</p>
 */
public final class Security {

    private Security() {
    }

    public static final int PAIRING_CODE_LENGTH = 6;
    private static final int PBKDF2_ITERATIONS = 12_000;
    private static final int KEY_BITS = 256;
    private static final String PBKDF2_ALGORITHM = "PBKDF2WithHmacSHA256";
    private static final String HMAC_ALGORITHM = "HmacSHA256";

    private static final SecureRandom RANDOM = new SecureRandom();

    /** 6-digit numeric pairing code, uniformly distributed (no modulo bias). */
    public static String newPairingCode() {
        StringBuilder sb = new StringBuilder(PAIRING_CODE_LENGTH);
        for (int i = 0; i < PAIRING_CODE_LENGTH; i++) {
            sb.append(RANDOM.nextInt(10));
        }
        return sb.toString();
    }

    public static byte[] randomBytes(int count) {
        byte[] out = new byte[count];
        RANDOM.nextBytes(out);
        return out;
    }

    /** 16-bit session tag stamped into datagram headers. */
    public static int newSessionTag() {
        return RANDOM.nextInt(0x10000);
    }

    /**
     * PBKDF2-HMAC-SHA256 over the pairing code.
     *
     * @param code 6-digit code typed on the client / displayed on the host
     * @param salt per-session random salt (16 bytes) generated by the host
     */
    public static byte[] deriveKeyFromCode(String code, byte[] salt) throws GeneralSecurityException {
        PBEKeySpec spec = new PBEKeySpec(code.toCharArray(), salt, PBKDF2_ITERATIONS, KEY_BITS);
        SecretKeyFactory factory = SecretKeyFactory.getInstance(PBKDF2_ALGORITHM);
        byte[] key = factory.generateSecret(spec).getEncoded();
        spec.clearPassword();
        return key;
    }

    /**
     * Final session key = HMAC(pairingKey, "session" | clientNonce | hostNonce).
     * Both sides can compute it, nobody else can without the code.
     */
    public static byte[] deriveSessionKey(byte[] pairingKey, byte[] clientNonce, byte[] hostNonce)
            throws GeneralSecurityException {
        Mac mac = newMac(pairingKey);
        mac.update("LGS-session-v1".getBytes(StandardCharsets.US_ASCII));
        mac.update(clientNonce);
        mac.update(hostNonce);
        return mac.doFinal();
    }

    /** Proof sent by the client while pairing: HMAC(pairingKey, "pair"|clientNonce|hostNonce). */
    public static byte[] pairingProof(byte[] pairingKey, byte[] clientNonce, byte[] hostNonce)
            throws GeneralSecurityException {
        Mac mac = newMac(pairingKey);
        mac.update("LGS-pair-v1".getBytes(StandardCharsets.US_ASCII));
        mac.update(clientNonce);
        mac.update(hostNonce);
        return mac.doFinal();
    }

    public static Mac newMac(byte[] key) throws GeneralSecurityException {
        Mac mac = Mac.getInstance(HMAC_ALGORITHM);
        mac.init(new SecretKeySpec(key, HMAC_ALGORITHM));
        return mac;
    }

    public static byte[] sha256(byte[] data) {
        try {
            return MessageDigest.getInstance("SHA-256").digest(data);
        } catch (GeneralSecurityException e) {
            throw new IllegalStateException("SHA-256 unavailable", e);
        }
    }

    /** Length-independent, constant-time comparison. */
    public static boolean constantTimeEquals(byte[] a, byte[] b) {
        if (a == null || b == null || a.length != b.length) {
            return false;
        }
        int diff = 0;
        for (int i = 0; i < a.length; i++) {
            diff |= a[i] ^ b[i];
        }
        return diff == 0;
    }

    /** Short human readable fingerprint of the session key (shown in the UI). */
    public static String fingerprint(byte[] sessionKey) {
        byte[] digest = sha256(sessionKey);
        StringBuilder sb = new StringBuilder(8);
        for (int i = 0; i < 4; i++) {
            sb.append(String.format("%02X", digest[i]));
        }
        return sb.toString();
    }
}
