include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: info

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_print: true
    require_trailing_commas: false
    use_super_parameters: true
