import { useEffect, useState } from 'react'
import { Sparkles, Loader2, RefreshCw, Wand2, Check } from 'lucide-react'
import { Modal } from '../ui/Modal'
import { Button, Field, Segmented, Select, Toggle } from '../ui/controls'
import { ai } from '../../services/ai-facade'
import { useEditorStore } from '../../state/editor-store'
import { useAppStore } from '../../state/app-store'
import { useUiStore, notify } from '../../state/ui-store'
import { createDocument, createPage, defaultBackground } from '../../../../shared/utils/document'
import type { DesignGeneratorOptions, DesignPlan } from '../../../../shared/types/ai'
import { DESIGN_SIZE_PRESETS } from '../../../../shared/constants'
import { newId } from '../../../../shared/utils/ids'
import type { GeneratedElement } from '../../../../shared/types/ai'

const STYLES = [
  { value: 'modern', label: 'Modern' },
  { value: 'minimal', label: 'Minimal' },
  { value: 'bold', label: 'Bold' },
  { value: 'vintage', label: 'Vintage' },
  { value: 'retro', label: 'Retro' },
  { value: 'elegant', label: 'Elegant' },
  { value: 'playful', label: 'Playful' },
  { value: 'corporate', label: 'Corporate' },
  { value: 'neon', label: 'Neon' }
] as const

const PALETTES = [
  { value: 'auto', label: 'Auto from prompt' },
  { value: 'vibrant', label: 'Vibrant' },
  { value: 'pastel', label: 'Pastel' },
  { value: 'mono', label: 'Monochrome' },
  { value: 'earth', label: 'Earth' },
  { value: 'neon', label: 'Neon' },
  { value: 'dark', label: 'Dark' }
] as const

const TYPOGRAPHY = [
  { value: 'auto', label: 'Auto' },
  { value: 'sans', label: 'Sans' },
  { value: 'serif', label: 'Serif' },
  { value: 'display', label: 'Display' },
  { value: 'script', label: 'Script' },
  { value: 'mono', label: 'Mono' }
] as const

const INITIAL: DesignGeneratorOptions = {
  prompt: '',
  style: 'modern',
  palette: 'auto',
  aspectRatio: '1:1',
  background: 'solid',
  typography: 'auto',
  complexity: 'balanced',
  useAiImages: false
}

export function AiDesignModal({ onClose, initialPrompt }: { onClose: () => void; initialPrompt?: string }): JSX.Element {
  const [options, setOptions] = useState<DesignGeneratorOptions>({ ...INITIAL, prompt: initialPrompt ?? '' })
  const [busy, setBusy] = useState(false)
  const [plan, setPlan] = useState<DesignPlan | null>(null)
  const [status, setStatus] = useState<string>('')
  const [replace, setReplace] = useState(false)
  const aiStatus = useAppStore((state) => state.aiStatus)

  useEffect(() => {
    if (initialPrompt && !plan && !busy) void generate()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const patch = <K extends keyof DesignGeneratorOptions>(key: K, value: DesignGeneratorOptions[K]): void =>
    setOptions((current) => ({ ...current, [key]: value }))

  const targetSize = (): { width: number; height: number } => {
    const preset = DESIGN_SIZE_PRESETS.find((entry) => entry.id === 'ig-post')
    void preset
    switch (options.aspectRatio) {
      case '16:9':
        return { width: 1920, height: 1080 }
      case '9:16':
        return { width: 1080, height: 1920 }
      case '4:5':
        return { width: 1080, height: 1350 }
      case '3:4':
        return { width: 1080, height: 1440 }
      case '2:3':
        return { width: 1080, height: 1620 }
      default:
        return { width: 1080, height: 1080 }
    }
  }

  const generate = async (): Promise<void> => {
    if (!options.prompt.trim()) {
      notify.warning('Describe the design you want first.')
      return
    }
    setBusy(true)
    setStatus('Composing layout…')
    try {
      const size = targetSize()
      const result = await ai.design({
        ...options,
        width: size.width,
        height: size.height,
        ...(options.seed ? {} : { seed: Math.floor(Math.random() * 1_000_000) })
      })
      setPlan(result)
      setStatus('')
    } catch (error) {
      notify.error('Design generation failed', error instanceof Error ? error.message : undefined)
    } finally {
      setBusy(false)
    }
  }

  const apply = (): void => {
    if (!plan) return
    const state = useEditorStore.getState()
    const size = targetSize()
    const page = createPage(size.width, size.height, 'AI page', plan.background ?? defaultBackground('#0F1024'))
    page.nodes = plan.elements.map((element) => element.node)
    const document = createDocument(size.width, size.height, 'AI page')
    document.pages = [page]

    if (replace || !state.document) {
      state.loadDocument(document)
    } else {
      state.addPage(page)
    }
    useUiStore.getState().requestFit()
    notify.success('Design placed on the canvas', plan.offline ? 'Generated with the offline engine' : `Generated by ${plan.provider}`)
    onClose()
  }

  const regenerateSlot = async (element: GeneratedElement): Promise<void> => {
    if (!plan) return
    setBusy(true)
    try {
      if (element.slot === 'hero' && element.regenerationHint) {
        const image = await ai.image({
          prompt: element.regenerationHint,
          aspectRatio: 'custom',
          width: Math.round(element.node.width),
          height: Math.round(element.node.height)
        })
        const state = useEditorStore.getState()
        const current = state.nodeById(element.node.id)
        if (current && current.kind === 'image') {
          state.updateNodes([{ id: current.id, patch: { src: image.dataUrl } }], { label: 'regenerate hero' })
          notify.success('Hero image regenerated')
        } else {
          notify.info('Add the design to the canvas first, then regenerate elements.')
        }
        return
      }
      const variants = await ai.text({
        task: element.slot === 'headline' ? 'headline' : element.slot === 'cta' ? 'slogans' : element.slot === 'body' ? 'product' : 'marketing',
        prompt: options.prompt,
        sourceText: element.node.kind === 'text' ? element.node.text : options.prompt,
        count: 1
      })
      const next = variants.variants[0]
      if (!next) return
      const state = useEditorStore.getState()
      const current = state.nodeById(element.node.id)
      if (current && current.kind === 'text') {
        state.updateNodes([{ id: current.id, patch: { text: next } }], { label: 'regenerate text' })
        notify.success('Element regenerated')
      } else if (element.node.kind === 'text') {
        setPlan({
          ...plan,
          elements: plan.elements.map((entry) =>
            entry.node.id === element.node.id && entry.node.kind === 'text'
              ? { ...entry, node: { ...entry.node, text: next } }
              : entry
          )
        })
        notify.success('Element regenerated — apply the design to see it')
      }
    } catch (error) {
      notify.error('Regeneration failed', error instanceof Error ? error.message : undefined)
    } finally {
      setBusy(false)
    }
  }

  return (
    <Modal
      title="AI design generator"
      subtitle="Describe the design — the app composes a real, editable layout."
      onClose={onClose}
      width={880}
      busy={busy}
      footer={
        <>
          <Button variant="ghost" onClick={onClose} disabled={busy}>
            Cancel
          </Button>
          <Button icon={Sparkles} disabled={busy || !options.prompt.trim()} onClick={() => void generate()}>
            {busy ? 'Generating…' : plan ? 'Regenerate' : 'Generate design'}
          </Button>
          <Button variant="primary" icon={Check} disabled={busy || !plan} onClick={apply}>
            {replace ? 'Replace page' : 'Add to canvas'}
          </Button>
        </>
      }
    >
      <div style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: 16 }}>
        <div className="k-col" style={{ gap: 12 }}>
          <Field label="Prompt">
            <textarea
              className="k-textarea"
              placeholder="Create a vintage Halloween t-shirt design with a cute raccoon"
              value={options.prompt}
              onChange={(event) => patch('prompt', event.target.value)}
              style={{ minHeight: 92 }}
            />
          </Field>
          <Field label="Style">
            <Select ariaLabel="Style" value={options.style} options={STYLES.map((entry) => ({ ...entry }))} onChange={(value) => patch('style', value)} />
          </Field>
          <Field label="Colour palette">
            <Select ariaLabel="Palette" value={options.palette} options={PALETTES.map((entry) => ({ ...entry }))} onChange={(value) => patch('palette', value)} />
          </Field>
          <Field label="Aspect ratio">
            <Segmented
              value={options.aspectRatio}
              options={[
                { value: '1:1', label: '1:1' },
                { value: '4:5', label: '4:5' },
                { value: '16:9', label: '16:9' },
                { value: '9:16', label: '9:16' },
                { value: '2:3', label: '2:3' }
              ]}
              onChange={(value) => patch('aspectRatio', value)}
            />
          </Field>
          <Field label="Background">
            <Segmented
              value={options.background}
              options={[
                { value: 'solid', label: 'Solid' },
                { value: 'gradient', label: 'Gradient' },
                { value: 'pattern', label: 'Pattern' },
                { value: 'transparent', label: 'None' }
              ]}
              onChange={(value) => patch('background', value)}
            />
          </Field>
          <Field label="Typography">
            <Select ariaLabel="Typography" value={options.typography} options={TYPOGRAPHY.map((entry) => ({ ...entry }))} onChange={(value) => patch('typography', value)} />
          </Field>
          <Field label="Complexity">
            <Segmented
              value={options.complexity}
              options={[
                { value: 'simple', label: 'Simple' },
                { value: 'balanced', label: 'Balanced' },
                { value: 'rich', label: 'Rich' }
              ]}
              onChange={(value) => patch('complexity', value)}
            />
          </Field>
          <Toggle
            label="Generate a hero image with AI"
            checked={options.useAiImages}
            onChange={(value) => patch('useAiImages', value)}
          />
          <Toggle label="Replace the current page instead of adding one" checked={replace} onChange={setReplace} />
          {aiStatus && !aiStatus.capabilities.image.configured ? (
            <p style={{ fontSize: 11, color: 'var(--k-text-mute)', margin: 0 }}>
              No image provider configured — hero images will be skipped and the layout will use shapes instead.
            </p>
          ) : null}
        </div>

        <div className="k-col" style={{ gap: 10, minHeight: 420 }}>
          {busy ? (
            <div className="k-col" style={{ gap: 10, alignItems: 'center', justifyContent: 'center', flex: 1 }}>
              <Loader2 size={22} className="k-spin" />
              <span style={{ color: 'var(--k-text-dim)' }}>{status || 'Working…'}</span>
            </div>
          ) : null}

          {!busy && !plan ? (
            <div className="k-empty" style={{ flex: 1, justifyContent: 'center' }}>
              <Wand2 size={22} />
              <span>Describe a design and press Generate</span>
              <span style={{ fontSize: 11.5, maxWidth: 340, lineHeight: 1.5 }}>
                The generator picks a layout archetype, palette and typography, writes the copy and places every element as a
                normal editable object.
              </span>
            </div>
          ) : null}

          {!busy && plan ? (
            <>
              <div className="k-row" style={{ gap: 8, flexWrap: 'wrap' }}>
                <span className="k-chip">{plan.archetype ?? 'layout'}</span>
                <span className={`k-chip ${plan.offline ? '' : 'k-chip--ok'}`}>{plan.offline ? 'Offline engine' : plan.provider}</span>
                <span className="k-chip">{plan.width}×{plan.height}</span>
                {plan.palette.map((color) => (
                  <span key={color} style={{ width: 14, height: 14, borderRadius: 4, background: color, border: '1px solid var(--k-line)' }} title={color} />
                ))}
              </div>
              <div
                className="k-panel k-checker"
                style={{ position: 'relative', aspectRatio: `${plan.width} / ${plan.height}`, maxHeight: 300, margin: '0 auto', width: '100%', overflow: 'hidden' }}
              >
                <div
                  style={{
                    position: 'absolute',
                    inset: 0,
                    background:
                      plan.background.type === 'transparent'
                        ? 'transparent'
                        : plan.background.type === 'gradient' && plan.background.gradient
                          ? `linear-gradient(${plan.background.gradient.angle ?? 90}deg, ${plan.background.gradient.stops?.[0]?.color}, ${plan.background.gradient.stops?.[1]?.color})`
                          : plan.background.color
                  }}
                />
                {plan.elements.map((element) => {
                  const node = element.node
                  const left = `${(node.x / plan.width) * 100}%`
                  const top = `${(node.y / plan.height) * 100}%`
                  const width = `${(node.width / plan.width) * 100}%`
                  const height = `${(node.height / plan.height) * 100}%`
                  if (node.kind === 'text') {
                    return (
                      <div
                        key={node.id}
                        style={{
                          position: 'absolute',
                          left,
                          top,
                          width,
                          height,
                          color: node.fill.type === 'solid' ? node.fill.color : node.fill.stops?.[0]?.color,
                          fontFamily: `${node.fontFamily}, Inter, sans-serif`,
                          fontSize: `max(6px, ${(node.fontSize / plan.height) * 100}%)`,
                          fontWeight: node.fontWeight,
                          letterSpacing: node.letterSpacing,
                          lineHeight: node.lineHeight,
                          textAlign: node.align,
                          display: 'flex',
                          alignItems: node.valign === 'top' ? 'flex-start' : node.valign === 'bottom' ? 'flex-end' : 'center',
                          overflow: 'hidden'
                        }}
                      >
                        <span style={{ width: '100%' }}>{node.text}</span>
                      </div>
                    )
                  }
                  if (node.kind === 'image') {
                    return (
                      <img
                        key={node.id}
                        src={node.src}
                        alt=""
                        style={{ position: 'absolute', left, top, width, height, objectFit: 'cover' }}
                      />
                    )
                  }
                  if (node.kind !== 'shape') return null
                  return (
                    <div
                      key={node.id}
                      style={{
                        position: 'absolute',
                        left,
                        top,
                        width,
                        height,
                        background: node.fill.type === 'solid' ? node.fill.color : `linear-gradient(${node.fill.angle ?? 90}deg, ${node.fill.stops?.[0]?.color}, ${node.fill.stops?.[1]?.color})`,
                        borderRadius: node.shape === 'circle' ? '50%' : node.cornerRadius ? `${node.cornerRadius}%` : 0,
                        clipPath: node.shape === 'triangle' ? 'polygon(50% 0,100% 100%,0 100%)' : undefined,
                        border: node.stroke ? `${node.stroke.width}px solid ${node.stroke.color}` : undefined
                      }}
                    />
                  )
                })}
              </div>

              <div className="k-sep" />
              <span className="k-section-title">Elements · regenerate individually</span>
              <div className="k-scroll" style={{ maxHeight: 150, display: 'grid', gap: 4 }}>
                {plan.elements.map((element) => (
                  <div key={`${element.node.id}-${newId('r')}`.slice(0, 24)} className="k-row-between" style={{ padding: '5px 8px', background: 'var(--k-panel-2)', borderRadius: 7 }}>
                    <span className="k-row" style={{ gap: 8, minWidth: 0 }}>
                      <span className="k-chip">{element.slot}</span>
                      <span className="k-truncate" style={{ fontSize: 12 }}>
                        {element.node.kind === 'text' ? element.node.text.slice(0, 46) : element.node.name}
                      </span>
                    </span>
                    <Button size="sm" variant="ghost" icon={RefreshCw} onClick={() => void regenerateSlot(element)} title="Regenerate this element">
                      Regenerate
                    </Button>
                  </div>
                ))}
              </div>
            </>
          ) : null}
        </div>
      </div>
    </Modal>
  )
}
