// Original, procedural block and item library for Neurio Blocks.
// The voxel-survival genre is familiar, but all names, palettes and recipes here are our own.

export const ID = Object.freeze({
  AIR: 0, GRASS: 1, DIRT: 2, STONE: 3, SAND: 4, LOG: 5, LEAVES: 6,
  PLANKS: 7, CRAFTING: 8, COBBLE: 9, COAL_ORE: 10, IRON_ORE: 11,
  GOLD_ORE: 12, DIAMOND_ORE: 13, REDSTONE_ORE: 14, WATER: 15,
  GLASS: 16, FURNACE: 17, TORCH: 18, SNOW: 19, GRAVEL: 20,
  OBSIDIAN: 21, CLAY: 22, SAPLING: 23, COAL: 24, RAW_IRON: 25,
  IRON_INGOT: 26, RAW_GOLD: 27, GOLD_INGOT: 28, DIAMOND: 29,
  REDSTONE: 30, STICK: 31, WOOD_PICK: 32, STONE_PICK: 33,
  IRON_PICK: 34, DIAMOND_PICK: 35, WOOD_AXE: 36, STONE_AXE: 37,
  IRON_AXE: 38, DIAMOND_AXE: 39, WOOD_SWORD: 40, STONE_SWORD: 41,
  IRON_SWORD: 42, DIAMOND_SWORD: 43, APPLE: 44, SEEDS: 45,
  WHEAT: 46, BREAD: 47, RAW_BEEF: 48, STEAK: 49, LEATHER: 50,
  WOOL: 51, EGG: 52, BONE: 53, CHEST: 54, BUCKET: 55,
  WATER_BUCKET: 56, BOOKSHELF: 57, CACTUS: 58, COPPER_ORE: 59,
  COPPER_INGOT: 60, LAPIS_ORE: 61, LAPIS: 62, DOOR: 63,
  BRICKS: 64, FLINT: 65, ARROW: 66, BOW: 67, SHIELD: 68,
  LEATHER_ARMOR: 69, IRON_ARMOR: 70, ROTTEN_FLESH: 71, RAW_COPPER: 72,
});

const item = (id, key, name, emoji, color, extra = {}) => ({ id, key, name, emoji, color, ...extra });

export const ITEMS = [
  item(ID.GRASS, 'grass', 'Grass block', '🌱', '#55a843', { placeable: true, block: true, category: 'blocks' }),
  item(ID.DIRT, 'dirt', 'Dirt', '🟫', '#8c6040', { placeable: true, block: true, category: 'blocks' }),
  item(ID.STONE, 'stone', 'Stone', '🪨', '#878b91', { placeable: true, block: true, category: 'blocks' }),
  item(ID.SAND, 'sand', 'Sand', '🏖️', '#d9c17a', { placeable: true, block: true, category: 'blocks' }),
  item(ID.LOG, 'log', 'Oak log', '🪵', '#855b36', { placeable: true, block: true, category: 'blocks' }),
  item(ID.LEAVES, 'leaves', 'Leaves', '🍃', '#478d4b', { placeable: true, block: true, category: 'blocks' }),
  item(ID.PLANKS, 'planks', 'Timber planks', '🪚', '#b58a54', { placeable: true, block: true, category: 'blocks' }),
  item(ID.CRAFTING, 'crafting', 'Work bench', '🧰', '#996333', { placeable: true, block: true, category: 'blocks' }),
  item(ID.COBBLE, 'cobble', 'Rough stone', '🧱', '#73777e', { placeable: true, block: true, category: 'blocks' }),
  item(ID.COAL_ORE, 'coalOre', 'Coal seam', '⚫', '#55575b', { placeable: true, block: true, category: 'blocks' }),
  item(ID.IRON_ORE, 'ironOre', 'Iron ore', '⛓️', '#9c7661', { placeable: true, block: true, category: 'blocks' }),
  item(ID.GOLD_ORE, 'goldOre', 'Gold ore', '🟨', '#c5a044', { placeable: true, block: true, category: 'blocks' }),
  item(ID.DIAMOND_ORE, 'diamondOre', 'Crystal ore', '💠', '#47d0c2', { placeable: true, block: true, category: 'blocks' }),
  item(ID.REDSTONE_ORE, 'redstoneOre', 'Red crystal ore', '🔴', '#a6353a', { placeable: true, block: true, category: 'blocks' }),
  item(ID.WATER, 'water', 'Water', '💧', '#398fe2', { placeable: true, block: true, category: 'blocks' }),
  item(ID.GLASS, 'glass', 'Glass', '🔷', '#9fe7ea', { placeable: true, block: true, category: 'blocks' }),
  item(ID.FURNACE, 'furnace', 'Stone kiln', '🔥', '#525257', { placeable: true, block: true, category: 'blocks' }),
  item(ID.TORCH, 'torch', 'Torch', '🕯️', '#edb847', { placeable: true, block: true, category: 'blocks' }),
  item(ID.SNOW, 'snow', 'Snow', '❄️', '#e7f3f6', { placeable: true, block: true, category: 'blocks' }),
  item(ID.GRAVEL, 'gravel', 'Gravel', '◽', '#88837f', { placeable: true, block: true, category: 'blocks' }),
  item(ID.OBSIDIAN, 'obsidian', 'Dark glassstone', '🟪', '#34263f', { placeable: true, block: true, category: 'blocks' }),
  item(ID.CLAY, 'clay', 'Clay', '🧱', '#a98278', { placeable: true, block: true, category: 'blocks' }),
  item(ID.SAPLING, 'sapling', 'Oak sapling', '🌿', '#63b85a', { placeable: true, block: true, category: 'blocks' }),
  item(ID.CACTUS, 'cactus', 'Cactus', '🌵', '#378644', { placeable: true, block: true, category: 'blocks' }),
  item(ID.COPPER_ORE, 'copperOre', 'Copper ore', '🟠', '#ad7251', { placeable: true, block: true, category: 'blocks' }),
  item(ID.LAPIS_ORE, 'lapisOre', 'Blue mineral ore', '🔵', '#3f5fa8', { placeable: true, block: true, category: 'blocks' }),
  item(ID.CHEST, 'chest', 'Storage crate', '📦', '#a57435', { placeable: true, block: true, category: 'blocks' }),
  item(ID.BOOKSHELF, 'bookshelf', 'Bookcase', '📚', '#836247', { placeable: true, block: true, category: 'blocks' }),
  item(ID.DOOR, 'door', 'Wooden door', '🚪', '#9a7044', { placeable: true, block: true, category: 'blocks' }),
  item(ID.BRICKS, 'bricks', 'Fired bricks', '🧱', '#ae6659', { placeable: true, block: true, category: 'blocks' }),
  item(ID.COAL, 'coal', 'Coal', '⚫', '#26272b', { category: 'resources' }),
  item(ID.RAW_IRON, 'rawIron', 'Raw iron', '⛓️', '#b78b73', { category: 'resources' }),
  item(ID.IRON_INGOT, 'ironIngot', 'Iron ingot', '🔩', '#c7c9cc', { category: 'resources' }),
  item(ID.RAW_GOLD, 'rawGold', 'Raw gold', '🟡', '#d5b44a', { category: 'resources' }),
  item(ID.GOLD_INGOT, 'goldIngot', 'Gold ingot', '🥇', '#efcb56', { category: 'resources' }),
  item(ID.DIAMOND, 'diamond', 'Sky crystal', '💎', '#55dfd4', { category: 'resources' }),
  item(ID.REDSTONE, 'redstone', 'Redstone dust', '🔴', '#d34242', { category: 'resources' }),
  item(ID.STICK, 'stick', 'Stick', '🥢', '#9d7249', { category: 'resources' }),
  item(ID.COPPER_INGOT, 'copperIngot', 'Copper ingot', '🟠', '#c77c53', { category: 'resources' }),
  item(ID.LAPIS, 'lapis', 'Blue mineral', '🔵', '#466ac0', { category: 'resources' }),
  item(ID.BUCKET, 'bucket', 'Empty bucket', '🪣', '#9da9b6', { category: 'tools' }),
  item(ID.WATER_BUCKET, 'waterBucket', 'Water bucket', '🪣', '#5798dd', { category: 'tools' }),
  item(ID.FLINT, 'flint', 'Flint shard', '🪨', '#46464d', { category: 'resources' }),
  item(ID.ARROW, 'arrow', 'Arrow', '🏹', '#927250', { category: 'tools' }),
  item(ID.BOW, 'bow', 'Bow', '🏹', '#a47c4d', { category: 'tools' }),
  item(ID.SHIELD, 'shield', 'Wood shield', '🛡️', '#9b7444', { category: 'tools' }),
  item(ID.WOOD_PICK, 'woodPick', 'Wood pick', '⛏️', '#a47548', { category: 'tools' }),
  item(ID.STONE_PICK, 'stonePick', 'Stone pick', '⛏️', '#888b91', { category: 'tools' }),
  item(ID.IRON_PICK, 'ironPick', 'Iron pick', '⛏️', '#ced1d5', { category: 'tools' }),
  item(ID.DIAMOND_PICK, 'diamondPick', 'Crystal pick', '⛏️', '#53d4cc', { category: 'tools' }),
  item(ID.WOOD_AXE, 'woodAxe', 'Wood axe', '🪓', '#a47548', { category: 'tools' }),
  item(ID.STONE_AXE, 'stoneAxe', 'Stone axe', '🪓', '#888b91', { category: 'tools' }),
  item(ID.IRON_AXE, 'ironAxe', 'Iron axe', '🪓', '#ced1d5', { category: 'tools' }),
  item(ID.DIAMOND_AXE, 'diamondAxe', 'Crystal axe', '🪓', '#53d4cc', { category: 'tools' }),
  item(ID.WOOD_SWORD, 'woodSword', 'Wood sword', '🗡️', '#a47548', { category: 'tools' }),
  item(ID.STONE_SWORD, 'stoneSword', 'Stone sword', '🗡️', '#888b91', { category: 'tools' }),
  item(ID.IRON_SWORD, 'ironSword', 'Iron sword', '🗡️', '#ced1d5', { category: 'tools' }),
  item(ID.DIAMOND_SWORD, 'diamondSword', 'Crystal sword', '🗡️', '#53d4cc', { category: 'tools' }),
  item(ID.APPLE, 'apple', 'Wild apple', '🍎', '#e55249', { category: 'food', food: 5 }),
  item(ID.SEEDS, 'seeds', 'Wild seeds', '🌾', '#b8a356', { category: 'resources' }),
  item(ID.WHEAT, 'wheat', 'Wheat', '🌾', '#d6bb58', { category: 'resources' }),
  item(ID.BREAD, 'bread', 'Bread', '🍞', '#c99653', { category: 'food', food: 7 }),
  item(ID.RAW_BEEF, 'rawBeef', 'Raw meat', '🥩', '#bd655b', { category: 'food' }),
  item(ID.STEAK, 'steak', 'Cooked meat', '🍖', '#a75b3b', { category: 'food', food: 8 }),
  item(ID.LEATHER, 'leather', 'Hide', '🟤', '#9b6947', { category: 'resources' }),
  item(ID.WOOL, 'wool', 'Soft wool', '☁️', '#eee8d8', { category: 'resources' }),
  item(ID.EGG, 'egg', 'Egg', '🥚', '#eee4cb', { category: 'food', food: 2 }),
  item(ID.BONE, 'bone', 'Bone', '🦴', '#e6e0ce', { category: 'resources' }),
  item(ID.ROTTEN_FLESH, 'rottenFlesh', 'Spoiled meat', '🟫', '#777044', { category: 'food', food: 1 }),
  item(ID.RAW_COPPER, 'rawCopper', 'Raw copper', '🟠', '#bb7650', { category: 'resources' }),
];

export const ITEM_BY_ID = new Map(ITEMS.map((x) => [x.id, x]));
export const ITEM_BY_KEY = new Map(ITEMS.map((x) => [x.key, x]));
export const MAX_STACK = 64;
export const MAX_Y = 64;
export const SEA_LEVEL = 12;
export const CHUNK_SIZE = 16;

const block = (id, hardness, tool, drop = id, extra = {}) => ({
  id, solid: true, hardness, tool, drop, ...extra,
});
export const BLOCK = Object.freeze({
  [ID.GRASS]: block(ID.GRASS, 0.65, 'shovel', ID.DIRT),
  [ID.DIRT]: block(ID.DIRT, 0.5, 'shovel'),
  [ID.STONE]: block(ID.STONE, 1.7, 'pick', ID.COBBLE, { minTool: 1 }),
  [ID.SAND]: block(ID.SAND, 0.45, 'shovel'),
  [ID.LOG]: block(ID.LOG, 1.15, 'axe'),
  [ID.LEAVES]: block(ID.LEAVES, 0.25, 'hand', ID.LEAVES),
  [ID.PLANKS]: block(ID.PLANKS, 0.85, 'axe'),
  [ID.CRAFTING]: block(ID.CRAFTING, 1.5, 'axe'),
  [ID.COBBLE]: block(ID.COBBLE, 2, 'pick', ID.COBBLE, { minTool: 1 }),
  [ID.COAL_ORE]: block(ID.COAL_ORE, 2.1, 'pick', ID.COAL, { minTool: 1, dropCount: [1, 2] }),
  [ID.IRON_ORE]: block(ID.IRON_ORE, 2.4, 'pick', ID.RAW_IRON, { minTool: 2 }),
  [ID.GOLD_ORE]: block(ID.GOLD_ORE, 2.8, 'pick', ID.RAW_GOLD, { minTool: 2 }),
  [ID.DIAMOND_ORE]: block(ID.DIAMOND_ORE, 3.2, 'pick', ID.DIAMOND, { minTool: 3 }),
  [ID.REDSTONE_ORE]: block(ID.REDSTONE_ORE, 2.7, 'pick', ID.REDSTONE, { minTool: 2, dropCount: [2, 4] }),
  [ID.WATER]: block(ID.WATER, 0, 'hand', ID.WATER, { solid: false, transparent: true }),
  [ID.GLASS]: block(ID.GLASS, 0.35, 'hand', ID.GLASS, { transparent: true }),
  [ID.FURNACE]: block(ID.FURNACE, 2.1, 'pick'),
  [ID.TORCH]: block(ID.TORCH, 0.1, 'hand', ID.TORCH, { solid: false, emissive: true }),
  [ID.SNOW]: block(ID.SNOW, 0.2, 'shovel'),
  [ID.GRAVEL]: block(ID.GRAVEL, 0.45, 'shovel', ID.GRAVEL),
  [ID.OBSIDIAN]: block(ID.OBSIDIAN, 8, 'pick', ID.OBSIDIAN, { minTool: 4 }),
  [ID.CLAY]: block(ID.CLAY, 0.6, 'shovel'),
  [ID.SAPLING]: block(ID.SAPLING, 0.1, 'hand', ID.SAPLING, { solid: false }),
  [ID.CACTUS]: block(ID.CACTUS, 0.55, 'axe'),
  [ID.COPPER_ORE]: block(ID.COPPER_ORE, 2, 'pick', ID.RAW_COPPER, { minTool: 1, dropCount: [1, 2] }),
  [ID.LAPIS_ORE]: block(ID.LAPIS_ORE, 2.2, 'pick', ID.LAPIS, { minTool: 1, dropCount: [2, 4] }),
  [ID.CHEST]: block(ID.CHEST, 1.4, 'axe'),
  [ID.BOOKSHELF]: block(ID.BOOKSHELF, 1.1, 'axe'),
  [ID.DOOR]: block(ID.DOOR, 0.8, 'axe'),
  [ID.BRICKS]: block(ID.BRICKS, 1.8, 'pick'),
});

export const TOOL_POWER = Object.freeze({
  [ID.WOOD_PICK]: { kind: 'pick', level: 1, speed: 2.2, damage: 2 },
  [ID.STONE_PICK]: { kind: 'pick', level: 2, speed: 3.1, damage: 3 },
  [ID.IRON_PICK]: { kind: 'pick', level: 3, speed: 4.5, damage: 4 },
  [ID.DIAMOND_PICK]: { kind: 'pick', level: 4, speed: 5.7, damage: 5 },
  [ID.WOOD_AXE]: { kind: 'axe', level: 1, speed: 3.1, damage: 4 },
  [ID.STONE_AXE]: { kind: 'axe', level: 2, speed: 4.3, damage: 5 },
  [ID.IRON_AXE]: { kind: 'axe', level: 3, speed: 5.4, damage: 6 },
  [ID.DIAMOND_AXE]: { kind: 'axe', level: 4, speed: 6.2, damage: 7 },
  [ID.WOOD_SWORD]: { kind: 'sword', level: 1, speed: 1.2, damage: 5 },
  [ID.STONE_SWORD]: { kind: 'sword', level: 2, speed: 1.2, damage: 7 },
  [ID.IRON_SWORD]: { kind: 'sword', level: 3, speed: 1.2, damage: 9 },
  [ID.DIAMOND_SWORD]: { kind: 'sword', level: 4, speed: 1.2, damage: 12 },
});

const recipe = (id, name, input, output, category = 'craft', note = '') => ({ id, name, input, output, category, note });
export const RECIPES = [
  recipe('planks', 'Timber planks ×4', { [ID.LOG]: 1 }, { [ID.PLANKS]: 4 }),
  recipe('sticks', 'Sticks ×4', { [ID.PLANKS]: 2 }, { [ID.STICK]: 4 }),
  recipe('bench', 'Work bench', { [ID.PLANKS]: 4 }, { [ID.CRAFTING]: 1 }),
  recipe('wood-pick', 'Wood pick', { [ID.PLANKS]: 3, [ID.STICK]: 2 }, { [ID.WOOD_PICK]: 1 }),
  recipe('wood-axe', 'Wood axe', { [ID.PLANKS]: 3, [ID.STICK]: 2 }, { [ID.WOOD_AXE]: 1 }),
  recipe('wood-sword', 'Wood sword', { [ID.PLANKS]: 2, [ID.STICK]: 1 }, { [ID.WOOD_SWORD]: 1 }),
  recipe('stone-pick', 'Stone pick', { [ID.COBBLE]: 3, [ID.STICK]: 2 }, { [ID.STONE_PICK]: 1 }),
  recipe('stone-axe', 'Stone axe', { [ID.COBBLE]: 3, [ID.STICK]: 2 }, { [ID.STONE_AXE]: 1 }),
  recipe('stone-sword', 'Stone sword', { [ID.COBBLE]: 2, [ID.STICK]: 1 }, { [ID.STONE_SWORD]: 1 }),
  recipe('iron-pick', 'Iron pick', { [ID.IRON_INGOT]: 3, [ID.STICK]: 2 }, { [ID.IRON_PICK]: 1 }),
  recipe('iron-axe', 'Iron axe', { [ID.IRON_INGOT]: 3, [ID.STICK]: 2 }, { [ID.IRON_AXE]: 1 }),
  recipe('iron-sword', 'Iron sword', { [ID.IRON_INGOT]: 2, [ID.STICK]: 1 }, { [ID.IRON_SWORD]: 1 }),
  recipe('diamond-pick', 'Crystal pick', { [ID.DIAMOND]: 3, [ID.STICK]: 2 }, { [ID.DIAMOND_PICK]: 1 }),
  recipe('diamond-axe', 'Crystal axe', { [ID.DIAMOND]: 3, [ID.STICK]: 2 }, { [ID.DIAMOND_AXE]: 1 }),
  recipe('diamond-sword', 'Crystal sword', { [ID.DIAMOND]: 2, [ID.STICK]: 1 }, { [ID.DIAMOND_SWORD]: 1 }),
  recipe('furnace', 'Stone kiln', { [ID.COBBLE]: 8 }, { [ID.FURNACE]: 1 }),
  recipe('torch', 'Torches ×4', { [ID.COAL]: 1, [ID.STICK]: 1 }, { [ID.TORCH]: 4 }),
  recipe('chest', 'Storage crate', { [ID.PLANKS]: 8 }, { [ID.CHEST]: 1 }),
  recipe('door', 'Wooden door', { [ID.PLANKS]: 6 }, { [ID.DOOR]: 3 }),
  recipe('bookshelf', 'Bookcase', { [ID.PLANKS]: 6, [ID.WHEAT]: 3 }, { [ID.BOOKSHELF]: 1 }),
  recipe('shield', 'Wood shield', { [ID.PLANKS]: 6, [ID.IRON_INGOT]: 1 }, { [ID.SHIELD]: 1 }),
  recipe('bucket', 'Empty bucket', { [ID.IRON_INGOT]: 3 }, { [ID.BUCKET]: 1 }),
  recipe('bread', 'Bread', { [ID.WHEAT]: 3 }, { [ID.BREAD]: 1 }),
  recipe('brick', 'Fired bricks ×4', { [ID.CLAY]: 4 }, { [ID.BRICKS]: 4 }, 'smelt', 'Fire clay in a kiln.'),
  recipe('smelt-iron', 'Iron ingot', { [ID.RAW_IRON]: 1, [ID.COAL]: 1 }, { [ID.IRON_INGOT]: 1 }, 'smelt', 'Fire raw ore with coal.'),
  recipe('smelt-gold', 'Gold ingot', { [ID.RAW_GOLD]: 1, [ID.COAL]: 1 }, { [ID.GOLD_INGOT]: 1 }, 'smelt', 'Fire raw ore with coal.'),
  recipe('smelt-copper', 'Copper ingot', { [ID.RAW_COPPER]: 1, [ID.COAL]: 1 }, { [ID.COPPER_INGOT]: 1 }, 'smelt', 'Refine copper with coal.'),
  recipe('glass', 'Glass', { [ID.SAND]: 1, [ID.COAL]: 1 }, { [ID.GLASS]: 1 }, 'smelt', 'Fire sand with coal.'),
  recipe('cook-meat', 'Cooked meat', { [ID.RAW_BEEF]: 1, [ID.COAL]: 1 }, { [ID.STEAK]: 1 }, 'smelt', 'Cook meat with coal.'),
];

export const DESCRIPTIONS = {
  [ID.GRASS]: 'A soft green surface. Great for building a home in the meadows.',
  [ID.DIRT]: 'Common earth. A shovel makes gathering it quicker.',
  [ID.STONE]: 'Hard rock. A pick is needed to collect rough stone.',
  [ID.SAND]: 'Loose grains found on coasts and in dry biomes.',
  [ID.LOG]: 'Timber harvested from trees. Turn it into planks and tools.',
  [ID.LEAVES]: 'Tree canopy. Break it for a chance to find seeds or apples.',
  [ID.COAL_ORE]: 'A useful fuel vein, usually found beneath hills.',
  [ID.IRON_ORE]: 'Raw metal that can be refined in a stone kiln.',
  [ID.GOLD_ORE]: 'A rare deep ore. Refine it before crafting.',
  [ID.DIAMOND_ORE]: 'A deep, uncommon crystal vein. Bring a strong pick.',
  [ID.WATER]: 'Clear water. Cross it carefully; shorelines can be slippery.',
  [ID.OBSIDIAN]: 'A very tough volcanic glassstone.',
  [ID.WOOD_PICK]: 'A first tool for stone and basic mineral veins.',
  [ID.IRON_PICK]: 'A reliable tool for harder ores and deep rock.',
  [ID.APPLE]: 'A wild snack that restores five hunger points.',
  [ID.BREAD]: 'A filling food made from gathered wheat.',
  [ID.FURNACE]: 'A stone kiln for refining metals and cooking food.',
  [ID.CRAFTING]: 'A sturdy bench for turning raw materials into useful gear.',
};

export function itemName(id) { return ITEM_BY_ID.get(Number(id))?.name || 'Unknown item'; }
export function itemEmoji(id) { return ITEM_BY_ID.get(Number(id))?.emoji || '▪️'; }
export function itemColor(id) { return ITEM_BY_ID.get(Number(id))?.color || '#888'; }
