// ── The Long Drive 3D — Vehicles, Buses, Parts, Landmarks & Graphics Presets ─

export const MOM_LETTER = {
  title: "LETTER FROM MOM",
  subtitle: "Pinned to the kitchen table — 1979",
  body: `My dearest child,

It has been months since the dry winds swallowed the cities. Everything out here is quiet now — just the endless desert highway, the humming telephone poles, and old wrecks left behind.

I am waiting for you at our family house at Kilometer 5,000.

Before you can hit the road, YOU MUST ASSEMBLE YOUR CAR in the garage:
1. Mount the ENGINE BLOCK and RADIATOR under the open front hood ([E] to pick up, [F] or Click on the engine bay to install).
2. Mount the 2 MISSING WHEELS onto the empty wheel hubs.
3. Pour GASOLINE into the rear-left fuel cap, MOTOR OIL into the engine, and WATER into the radiator! (Or open [Tab] Mechanic near the car for quick assembly).
4. Pack extra jerrycans, oil, water, food, and Repair Kits into your TRUNK.
5. Along the long highway — separated by long, unpredictable stretches of desert — you will discover abandoned Houses (Dyor), grand Desert Palaces & Mansions (Qusoor), Kasbah Oasis Forts, Gas Stations (Mahatat), and Bus Terminals!
6. If you are lucky, you will find a Muscle V8, a Military Truck, or a giant IKARUS HIGHWAY BUS — they may be broken down, but if you have the parts, tools, and fluids, you can repair them and drive them instead!

Drive safe, keep the radio playing, and come home soon.

With all my love,
— Mom ❤️`
};

// ── Graphics Quality Presets (Low / Medium / High / Very High / Ultra / Extreme) ──
export const GRAPHICS_PRESETS = {
  low: {
    id: 'low',
    label: 'Low (Performance)',
    resScale: 0.75,
    shadows: false,
    shadowMapSize: 512,
    shadowDist: 40,
    bloom: false,
    bloomStrength: 0.0,
    chromatic: 0.0,
    grain: 0.0,
    anisotropy: 1,
    chunkForward: 5,
    chunkBackward: 3,
    msaa: 0,
    contactShadow: true,
  },
  medium: {
    id: 'medium',
    label: 'Medium (Balanced)',
    resScale: 1.0,
    shadows: true,
    shadowMapSize: 1024,
    shadowDist: 50,
    bloom: false,
    bloomStrength: 0.35,
    chromatic: 0.0,
    grain: 0.0,
    anisotropy: 4,
    chunkForward: 7,
    chunkBackward: 4,
    msaa: 0,
    contactShadow: true,
  },
  high: {
    id: 'high',
    label: 'High (HD 1080p)',
    resScale: 1.25,
    shadows: true,
    shadowMapSize: 2048,
    shadowDist: 68,
    bloom: true,
    bloomStrength: 0.48,
    chromatic: 0.0015,
    grain: 0.01,
    anisotropy: 8,
    chunkForward: 9,
    chunkBackward: 5,
    msaa: 2,
    contactShadow: true,
  },
  very_high: {
    id: 'very_high',
    label: 'Very High (QHD 1440p)',
    resScale: 1.5,
    shadows: true,
    shadowMapSize: 2048,
    shadowDist: 85,
    bloom: true,
    bloomStrength: 0.55,
    chromatic: 0.0025,
    grain: 0.015,
    anisotropy: 8,
    chunkForward: 11,
    chunkBackward: 6,
    msaa: 4,
    contactShadow: true,
  },
  ultra: {
    id: 'ultra',
    label: 'Ultra (4K UHD SuperSampled)',
    resScale: 1.85,
    shadows: true,
    shadowMapSize: 4096,
    shadowDist: 110,
    bloom: true,
    bloomStrength: 0.62,
    chromatic: 0.0032,
    grain: 0.018,
    anisotropy: 16,
    chunkForward: 13,
    chunkBackward: 7,
    msaa: 4,
    contactShadow: true,
  },
  extreme: {
    id: 'extreme',
    label: 'Extreme (4K Max Horizon + Ultra Shadows)',
    resScale: 2.25,
    shadows: true,
    shadowMapSize: 4096,
    shadowDist: 145,
    bloom: true,
    bloomStrength: 0.68,
    chromatic: 0.0038,
    grain: 0.022,
    anisotropy: 16,
    chunkForward: 16,
    chunkBackward: 8,
    msaa: 4,
    contactShadow: true,
  },
};

// ── 8 Detailed Vehicle & Bus Archetypes ──────────────────────────────────────
export const CAR_ARCHETYPES = [
  {
    id: 'sedan',
    name: 'VAZ-2101 "Zhiguli" Classic Sedan',
    desc: 'Iconic boxy Eastern-European sedan with twin chrome round headlights, chrome bumpers, and balanced fuel economy.',
    length: 4.35,
    width: 1.74,
    chassisY: 0.42,
    cabinHeight: 0.72,
    fuelCap: 42,
    massKg: 1020,
    defaultEngine: 'eng_i4_1200',
    defaultRadiator: 'rad_std',
    defaultColor: '#c94a38',
    trunkSlots: 6,
    seatOffset: { x: -0.42, y: 1.08, z: 0.1 },
    hoodZ: 1.38,
    trunkZ: -1.55,
    wheelBase: 2.62,
    trackWidth: 1.50,
    rarity: 'common',
  },
  {
    id: 'bus',
    name: 'Ikarus 260 Highway Coach Bus',
    desc: 'Massive 8.4-meter city & desert transit bus! Accordion doors, rooftop AC pods, 120L tank, 12 cargo slots, unstoppable momentum.',
    length: 8.4,
    width: 2.36,
    chassisY: 0.52,
    cabinHeight: 1.52,
    fuelCap: 120,
    massKg: 6400,
    defaultEngine: 'eng_diesel_6500',
    defaultRadiator: 'rad_heavy',
    defaultColor: '#eab308',
    trunkSlots: 12,
    seatOffset: { x: -0.70, y: 1.64, z: 3.25 },
    hoodZ: 3.65,
    trunkZ: -3.75,
    wheelBase: 5.05,
    trackWidth: 2.02,
    rarity: 'legendary',
  },
  {
    id: 'megabus',
    name: 'Ikarus 280 Royal Desert Liner',
    desc: 'Ultra-rare 10.2-meter luxury long-distance coach bus! Rooftop luggage rack, dual-turbo diesel power, 160L fuel tank, 15 cargo slots.',
    length: 10.2,
    width: 2.42,
    chassisY: 0.54,
    cabinHeight: 1.56,
    fuelCap: 160,
    massKg: 7800,
    defaultEngine: 'eng_diesel_6500',
    defaultRadiator: 'rad_heavy',
    defaultColor: '#2b6cb0',
    trunkSlots: 15,
    seatOffset: { x: -0.72, y: 1.68, z: 4.10 },
    hoodZ: 4.50,
    trunkZ: -4.60,
    wheelBase: 6.20,
    trackWidth: 2.08,
    rarity: 'legendary',
  },
  {
    id: 'muscle',
    name: 'Plymouth "Fury V8" Highway Interceptor',
    desc: 'Aggressive American V8 muscle coupe with hood power-scoop, rear spoiler, quad headlights, and 200+ km/h top speed.',
    length: 4.92,
    width: 1.90,
    chassisY: 0.40,
    cabinHeight: 0.66,
    fuelCap: 68,
    massKg: 1580,
    defaultEngine: 'eng_v8_5000',
    defaultRadiator: 'rad_heavy',
    defaultColor: '#d97706',
    trunkSlots: 6,
    seatOffset: { x: -0.46, y: 1.04, z: -0.05 },
    hoodZ: 1.60,
    trunkZ: -1.80,
    wheelBase: 2.98,
    trackWidth: 1.64,
    rarity: 'rare',
  },
  {
    id: 'truck',
    name: 'GAZ-66 "Steppe" 4x4 Heavy Cargo Truck',
    desc: 'Heavy military expedition truck with bullbar, roof spotlights, high ground clearance, 95L tank, and 12-slot flatbed.',
    length: 5.85,
    width: 2.15,
    chassisY: 0.58,
    cabinHeight: 0.96,
    fuelCap: 95,
    massKg: 3400,
    defaultEngine: 'eng_diesel_6500',
    defaultRadiator: 'rad_heavy',
    defaultColor: '#3b7a57',
    trunkSlots: 12,
    seatOffset: { x: -0.56, y: 1.46, z: 1.10 },
    hoodZ: 2.15,
    trunkZ: -2.20,
    wheelBase: 3.65,
    trackWidth: 1.84,
    rarity: 'rare',
  },
  {
    id: 'pickup',
    name: 'Dacia "Hauler" Off-Road Pickup',
    desc: 'Rugged utility pickup truck with cab rollbar, roof lights, and an 8-slot open timber cargo bed.',
    length: 4.72,
    width: 1.84,
    chassisY: 0.50,
    cabinHeight: 0.78,
    fuelCap: 58,
    massKg: 1340,
    defaultEngine: 'eng_i4_1800',
    defaultRadiator: 'rad_std',
    defaultColor: '#b45309',
    trunkSlots: 8,
    seatOffset: { x: -0.44, y: 1.20, z: 0.35 },
    hoodZ: 1.52,
    trunkZ: -1.58,
    wheelBase: 2.88,
    trackWidth: 1.58,
    rarity: 'uncommon',
  },
  {
    id: 'van',
    name: 'Barkas B1000 Expedition Camper Van',
    desc: 'Forward-control desert nomad van with roof expedition rack, spare tire mount, and 10-slot cargo bay.',
    length: 4.65,
    width: 1.88,
    chassisY: 0.48,
    cabinHeight: 1.08,
    fuelCap: 62,
    massKg: 1450,
    defaultEngine: 'eng_i4_1800',
    defaultRadiator: 'rad_heavy',
    defaultColor: '#14b8a6',
    trunkSlots: 10,
    seatOffset: { x: -0.45, y: 1.34, z: 1.15 },
    hoodZ: 1.65,
    trunkZ: -1.75,
    wheelBase: 2.75,
    trackWidth: 1.60,
    rarity: 'rare',
  },
  {
    id: 'buggy',
    name: 'Baja 1000 Tube-Frame Dune Buggy',
    desc: 'Ultra-lightweight desert racer with tubular roll-cage, roof LED bar, and miserly fuel consumption.',
    length: 3.95,
    width: 1.72,
    chassisY: 0.46,
    cabinHeight: 0.70,
    fuelCap: 38,
    massKg: 780,
    defaultEngine: 'eng_i4_1800',
    defaultRadiator: 'rad_std',
    defaultColor: '#e11d48',
    trunkSlots: 4,
    seatOffset: { x: -0.38, y: 1.10, z: 0.0 },
    hoodZ: 1.25,
    trunkZ: -1.40,
    wheelBase: 2.40,
    trackWidth: 1.52,
    rarity: 'uncommon',
  },
];

export const CAR_BY_ID = Object.fromEntries(CAR_ARCHETYPES.map((c) => [c.id, c]));

// ── Swappable Car & Bus Engines ──────────────────────────────────────────────
export const ENGINES = {
  eng_i4_1200: {
    id: 'eng_i4_1200',
    name: '1.2L Zhiguli Inline-4 Engine',
    hp: 68,
    topSpeedKmh: 132,
    accel: 12.2,
    fuelRate: 0.045,
    oilCap: 3.5,
    heatRate: 1.0,
    pitch: 1.0,
  },
  eng_i4_1800: {
    id: 'eng_i4_1800',
    name: '1.8L Twin-Cam Rally Engine',
    hp: 118,
    topSpeedKmh: 164,
    accel: 16.0,
    fuelRate: 0.060,
    oilCap: 4.2,
    heatRate: 1.12,
    pitch: 1.15,
  },
  eng_diesel_6500: {
    id: 'eng_diesel_6500',
    name: '6.5L Rába-MAN Bus Turbo-Diesel',
    hp: 210,
    topSpeedKmh: 148,
    accel: 15.2,
    fuelRate: 0.072,
    oilCap: 6.5,
    heatRate: 1.05,
    pitch: 0.62,
  },
  eng_v8_5000: {
    id: 'eng_v8_5000',
    name: '5.0L Fury V8 Supercharged Engine',
    hp: 265,
    topSpeedKmh: 210,
    accel: 23.5,
    fuelRate: 0.090,
    oilCap: 5.5,
    heatRate: 1.35,
    pitch: 0.74,
  },
};

export const RADIATORS = {
  rad_rusty: {
    id: 'rad_rusty',
    name: 'Rusty Salvage Radiator',
    waterCap: 5.0,
    coolingPower: 0.75,
  },
  rad_std: {
    id: 'rad_std',
    name: 'Standard Fin Radiator',
    waterCap: 8.5,
    coolingPower: 1.15,
  },
  rad_heavy: {
    id: 'rad_heavy',
    name: 'Heavy-Duty Copper V8/Bus Radiator',
    waterCap: 15.0,
    coolingPower: 1.85,
  },
};

export const PAINT_COLORS = [
  { name: 'Faded Soviet Red', hex: '#c94a38' },
  { name: 'Ikarus Bus Yellow', hex: '#eab308' },
  { name: 'Sahara Ochre', hex: '#d97706' },
  { name: 'Steppe Olive', hex: '#3b7a57' },
  { name: 'Baltic Blue', hex: '#2b6cb0' },
  { name: 'Desert Sand', hex: '#d6bfa3' },
  { name: 'Midnight Black', hex: '#1f242d' },
  { name: 'Mint Turquoise', hex: '#14b8a6' },
  { name: 'Crimson Rose', hex: '#e11d48' },
  { name: 'Chrome Silver', hex: '#cbd5e1' },
];

// ── Item, Tool & Part Definitions ────────────────────────────────────────────
export const ITEM_DEFS = {
  jerrycan_gas: {
    id: 'jerrycan_gas',
    name: 'Gasoline Jerrycan (20L)',
    icon: '⛽',
    category: 'fluid',
    fluidType: 'gas',
    capacity: 20.0,
    defaultAmount: 18.0,
    desc: 'Steel 20L jerrycan for fuel. Look at your car fuel cap and press [F] or Click to pour.',
  },
  oil_can: {
    id: 'oil_can',
    name: 'Motor Oil Can (4L)',
    icon: '🛢️',
    category: 'fluid',
    fluidType: 'oil',
    capacity: 4.0,
    defaultAmount: 3.5,
    desc: '10W-40 Motor Oil. Open the hood, look at the engine block, and press [F] or Click to pour.',
  },
  water_jug: {
    id: 'water_jug',
    name: 'Water Jug (10L)',
    icon: '💧',
    category: 'fluid',
    fluidType: 'water',
    capacity: 10.0,
    defaultAmount: 9.0,
    desc: 'Clean water for cooling your car radiator OR drinking ([F] to drink / pour into radiator).',
  },
  canteen: {
    id: 'canteen',
    name: 'Desert Canteen (2.5L)',
    icon: '🍶',
    category: 'fluid',
    fluidType: 'water',
    capacity: 2.5,
    defaultAmount: 2.5,
    desc: 'Personal water canteen. Quenches thirst or tops up a steaming radiator in a pinch.',
  },
  salami: {
    id: 'salami',
    name: 'Hungarian Salami Stick',
    icon: '🌭',
    category: 'food',
    hunger: 48,
    thirst: -5,
    health: 15,
    desc: 'Cured road-trip salami. Never spoils in the desert heat. (+48 Food, +15 HP)',
  },
  beans: {
    id: 'beans',
    name: 'Canned Baked Beans',
    icon: '🥫',
    category: 'food',
    hunger: 38,
    thirst: 12,
    health: 12,
    desc: 'Tin of hearty beans in tomato sauce. (+38 Food, +12 Water, +12 HP)',
  },
  chocolate: {
    id: 'chocolate',
    name: 'Cosmonaut Chocolate Bar',
    icon: '🍫',
    category: 'food',
    hunger: 30,
    thirst: 0,
    health: 15,
    desc: 'High-energy dark chocolate ration. (+30 Food, +15 HP)',
  },
  soda: {
    id: 'soda',
    name: 'Warm Sunset Cola',
    icon: '🥤',
    category: 'food',
    hunger: 10,
    thirst: 48,
    health: 10,
    desc: 'Fizzy soda bottle. Great for desert thirst! (+48 Water, +10 Food)',
  },
  medkit: {
    id: 'medkit',
    name: 'First-Aid Field Kit',
    icon: '🧰',
    category: 'food',
    hunger: 0,
    thirst: 0,
    health: 70,
    desc: 'Bandages and antiseptic for crash injuries and rabbit bites. (+70 HP)',
  },
  repair_kit: {
    id: 'repair_kit',
    name: 'Mechanic Wrench & Parts Kit',
    icon: '🔧',
    category: 'tool',
    uses: 5,
    desc: 'Repairs broken/wrecked engines, radiators, tires & chassis on abandoned cars and buses! ([F] or Click on vehicle)',
  },
  wire_brush: {
    id: 'wire_brush',
    name: 'Steel Wire Brush',
    icon: '🪥',
    category: 'tool',
    uses: 30,
    desc: 'Scrub rust off car body panels, engines, radiators, and wheels to restore 100% mint condition!',
  },
  spray_paint: {
    id: 'spray_paint',
    name: 'Aerosol Spray Paint',
    icon: '🎨',
    category: 'tool',
    uses: 15,
    desc: 'Respray your car or bus body with a fresh coat of desert paint! Hold [F] or Click on vehicle.',
  },
  siphon_hose: {
    id: 'siphon_hose',
    name: 'Rubber Siphon Hose',
    icon: '➰',
    category: 'tool',
    uses: 99,
    desc: 'Transfer fuel or water from abandoned vehicles and station pumps straight into your containers.',
  },
  revolver: {
    id: 'revolver',
    name: '.357 Desert Revolver',
    icon: '🔫',
    category: 'weapon',
    ammo: 18,
    damage: 60,
    desc: 'Six-shooter for defending against rabid mutant desert hares. Left-Click to fire.',
  },
  binoculars: {
    id: 'binoculars',
    name: 'Field Binoculars (6x)',
    icon: '🔭',
    category: 'tool',
    uses: 999,
    desc: 'Hold [F] or Right-Click to zoom 6x and spot distant Palaces, Houses, and Bus Terminals.',
  },
  part_wheel: {
    id: 'part_wheel',
    name: 'All-Terrain Wheel & Tire',
    icon: '🛞',
    category: 'part',
    partSlot: 'wheel',
    desc: 'Wheel & tire assembly. Look at any empty wheel hub on a car or bus and press [F] to mount.',
  },
  part_engine_std: {
    id: 'part_engine_std',
    name: '1.2L Zhiguli Inline-4 Engine',
    icon: '⚙️',
    category: 'part',
    partSlot: 'engine',
    engineId: 'eng_i4_1200',
    desc: 'Reliable 68 HP 4-cylinder starter engine. Open hood and press [F] on engine bay to install.',
  },
  part_engine_i4: {
    id: 'part_engine_i4',
    name: '1.8L Twin-Cam Rally Engine',
    icon: '⚙️',
    category: 'part',
    partSlot: 'engine',
    engineId: 'eng_i4_1800',
    desc: 'High-revving 118 HP 4-cylinder engine. Open hood and press [F] on engine bay to swap.',
  },
  part_engine_diesel: {
    id: 'part_engine_diesel',
    name: '6.5L Bus Turbo-Diesel Engine',
    icon: '🚌',
    category: 'part',
    partSlot: 'engine',
    engineId: 'eng_diesel_6500',
    desc: 'High-torque 210 HP heavy turbo-diesel engine from an Ikarus Bus. Fits any engine bay!',
  },
  part_engine_v8: {
    id: 'part_engine_v8',
    name: '5.0L Fury V8 Muscle Engine',
    icon: '🔥',
    category: 'part',
    partSlot: 'engine',
    engineId: 'eng_v8_5000',
    desc: 'Monster 265 HP V8 muscle block! Fits in any chassis with the hood open. [F] to swap.',
  },
  part_radiator_std: {
    id: 'part_radiator_std',
    name: 'Standard Fin Radiator',
    icon: '🌡️',
    category: 'part',
    partSlot: 'radiator',
    radiatorId: 'rad_std',
    desc: '8.5L automotive radiator. Open hood and press [F] on radiator mount to install.',
  },
  part_radiator_heavy: {
    id: 'part_radiator_heavy',
    name: 'Heavy-Duty Copper Radiator',
    icon: '🧊',
    category: 'part',
    partSlot: 'radiator',
    radiatorId: 'rad_heavy',
    desc: '15L dual-core copper radiator for V8s and Buses. Keeps engines cool across noon dunes!',
  },
};

let _nextItemUid = 1;
export function createItemInstance(defId, overrides = {}) {
  const def = ITEM_DEFS[defId];
  if (!def) throw new Error('Unknown item def: ' + defId);
  const paintChoice = overrides.paintHex || PAINT_COLORS[(_nextItemUid * 3) % PAINT_COLORS.length].hex;
  const paintName = overrides.paintName || PAINT_COLORS.find((p) => p.hex === paintChoice)?.name || 'Custom';
  return {
    uid: 'itm_' + (_nextItemUid++),
    defId: def.id,
    name: def.id === 'spray_paint' ? `Spray Paint (${paintName})` : def.name,
    icon: def.icon,
    category: def.category,
    fluidType: def.fluidType || null,
    capacity: def.capacity || 0,
    amount: overrides.amount !== undefined ? overrides.amount : (def.defaultAmount || 0),
    condition: overrides.condition !== undefined ? overrides.condition : 0.85,
    uses: overrides.uses !== undefined ? overrides.uses : (def.uses || 1),
    ammo: overrides.ammo !== undefined ? overrides.ammo : (def.ammo || 0),
    paintHex: paintChoice,
    engineId: overrides.engineId || def.engineId || null,
    radiatorId: overrides.radiatorId || def.radiatorId || null,
    partSlot: def.partSlot || null,
  };
}

// ── Car Radio Stations ───────────────────────────────────────────────────────
export const RADIO_STATIONS = [
  {
    freq: '88.7 FM',
    name: 'MIRAGE SYNTH',
    genre: 'Outrun / Desert Synthwave',
    djLine: 'Broadcasting solar waves across Sector 7... keep your eyes on the poles.',
    mode: 'synthwave',
  },
  {
    freq: '94.3 FM',
    name: 'DUSTBOWL TWANG',
    genre: 'Highway Country & Blues',
    djLine: 'If your radiator is boiling, pull over at the next oasis or palace, friend.',
    mode: 'country',
  },
  {
    freq: '101.5 FM',
    name: 'OASIS LOUNGE',
    genre: 'Sunset Rhodes & Chill',
    djLine: 'Smooth grooves for 5,000 kilometers of open asphalt.',
    mode: 'chill',
  },
  {
    freq: '105.9 FM',
    name: 'CIVIL DEFENSE',
    genre: 'Emergency Numbers & Static',
    djLine: 'ATTENTION TRAVELERS: Avoid rabid lagomorphs. Check engine oil every 10 km.',
    mode: 'numbers',
  },
];

// ── Diverse Roadside Landmarks: Houses (Dyor), Palaces (Qusoor), Kasbahs, Bus Depots & Stations ──
export const POI_TYPES = [
  {
    id: 'desert_palace',
    name: 'Abandoned Desert Palace (Qasr Al-Sahra)',
    signText: 'ROYAL PALACE',
    archStyle: 'palace',
    hasWaterTower: true,
    spawnCarChance: 0.88,
    preferRare: true,
  },
  {
    id: 'desert_house',
    name: 'Two-Story Desert House & Barn (Dar)',
    signText: 'OLD HOMESTEAD',
    archStyle: 'house',
    hasGarage: true,
    spawnCarChance: 0.58,
  },
  {
    id: 'kasbah_oasis',
    name: 'Ancient Kasbah Watchtower & Oasis Well',
    signText: 'KASBAH OASIS',
    archStyle: 'kasbah',
    hasWaterTower: true,
    spawnCarChance: 0.52,
  },
  {
    id: 'bus_depot',
    name: 'Ikarus Highway Bus Terminal & Hangar',
    signText: 'BUS TERMINAL',
    archStyle: 'depot',
    hasFuelPump: true,
    hasGarage: true,
    spawnCarChance: 0.95,
    preferBus: true,
  },
  {
    id: 'gas_station',
    name: 'Vintage Highway Gas Station (Mahata)',
    signText: 'DESERT FUEL',
    archStyle: 'station',
    hasFuelPump: true,
    hasGarage: true,
    spawnCarChance: 0.65,
  },
  {
    id: 'wreck_garage',
    name: 'Heavy Truck & Auto Salvage Yard',
    signText: 'AUTO SALVAGE',
    archStyle: 'garage',
    hasGarage: true,
    hasRadioTower: true,
    spawnCarChance: 0.95,
  },
];
