"""Build the single-file Windows installer for MotionForge Studio.

The installer is a small PyInstaller bundle (its own Python + the Tk wizard)
with the *portable build ZIP appended to the executable*.  Reading the payload
straight out of ``sys.executable`` with :mod:`zipfile` means the setup starts in
about a second and streams the ~100 MB payload to disk with a progress bar -
no temporary copy of the archive is ever made.

    tools/devrun.sh tools/build_win_installer.py dist/MotionForge-Studio-1.0.0-win64-portable.zip

PyInstaller is a build-time dependency only; it is not shipped to users.  Its
own ``--icon``/``--version-file`` options write the Windows resources, so the
finished executable is never edited by hand - on a ~110 MB file that is the one
step that can produce something Windows refuses to start.
"""
from __future__ import annotations

import os
import shutil
import struct
import subprocess
import sys
import tempfile
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INSTALLER_DIR = os.path.join(ROOT, "packaging", "win", "installer")
ICON = os.path.join(ROOT, "packaging", "win", "motionforge.ico")
UTF16_VERSION_FILE = os.path.join(INSTALLER_DIR, "version_info.txt")


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\")


def write_version_file(version, app_exe: str = "MotionForge-Studio-Setup") -> str:
    """PyInstaller version resource description (Windows only)."""
    app_exe = app_exe[:-4] if app_exe.lower().endswith(".exe") else app_exe
    ver = ".".join(str(p) for p in version)
    ver4 = f"({version[0]}, {version[1]}, {version[2]}, 0)"
    text = f'''VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={ver4}, prodvers={ver4}, mask=0x3f, flags=0x0, OS=0x40004,
    fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
        StringStruct('CompanyName', 'MotionForge Labs'),
        StringStruct('FileDescription', 'MotionForge Studio 2D animation studio - setup'),
        StringStruct('FileVersion', '{ver}'),
        StringStruct('InternalName', '{app_exe}'),
        StringStruct('LegalCopyright', 'Copyright (C) 2026 MotionForge Labs'),
        StringStruct('OriginalFilename', '{app_exe}.exe'),
        StringStruct('ProductName', 'MotionForge Studio'),
        StringStruct('ProductVersion', '{ver} (Windows x64)'),
        StringStruct('Comments', 'Installs the portable MotionForge Studio build, shortcuts and uninstaller.')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
'''
    with open(UTF16_VERSION_FILE, "w", encoding="utf-8") as fh:
        fh.write(text)
    return UTF16_VERSION_FILE


def append_payload(exe: str, zip_path: str) -> int:
    """Append the portable ZIP to the installer executable."""
    with open(exe, "ab") as out, open(zip_path, "rb") as src:
        shutil.copyfileobj(src, out, 1024 * 512)
    return os.path.getsize(exe)


def build_installer(zip_path: str, out_dir: str, version, icon_path: str = ICON,
                    app_exe: str = "MotionForge Studio.exe") -> str:
    """Create ``MotionForge-Studio-Setup-<ver>.exe`` and return its path."""
    os.makedirs(out_dir, exist_ok=True)
    name = f"MotionForge-Studio-Setup-{'.'.join(str(p) for p in version)}"
    work = tempfile.mkdtemp(prefix="mfs-setup-")

    # the installer needs to know which executable to launch and how to find the
    # payload; keep that in one small generated file
    with open(os.path.join(INSTALLER_DIR, "build_info.py"), "w", encoding="utf-8") as fh:
        fh.write(f'"""Generated by tools/build_win_installer.py - do not edit."""\n'
                 f'APP_EXE = "{app_exe}"\n'
                 f'VERSION = "{".".join(str(p) for p in version)}"\n')

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean", "--onefile", "--windowed",
        "--name", name,
        "--distpath", os.path.join(work, "dist"),
        "--workpath", os.path.join(work, "build"),
        "--specpath", work,
        "--paths", INSTALLER_DIR,
        "--hidden-import", "tkinter",
        "--hidden-import", "tkinter.ttk",
        "--hidden-import", "tkinter.filedialog",
        "--hidden-import", "winreg",
        "--collect-submodules", "tkinter",
        os.path.join(INSTALLER_DIR, "installer.py"),
    ]
    if os.path.exists(icon_path):
        cmd += ["--icon", icon_path]
    version_file = write_version_file(version, name)
    if os.path.exists(version_file):
        cmd += ["--version-file", version_file]
    print("  pyinstaller ...")
    started = time.time()
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    if proc.returncode != 0:
        tail = "\n".join((proc.stdout or "").splitlines()[-25:])
        raise SystemExit(f"PyInstaller failed ({proc.returncode}):\n{proc.stderr}\n{tail}")
    built = os.path.join(work, "dist", name + ".exe")
    if not os.path.exists(built):
        built = os.path.join(work, "dist", name)
    if not os.path.exists(built):
        raise SystemExit("PyInstaller did not produce an executable")
    print(f"    bundle built in {time.time() - started:.0f}s "
          f"({os.path.getsize(built) / 1e6:.1f} MB)")

    final = os.path.join(out_dir, name + ".exe")
    shutil.copy2(built, final)
    size = append_payload(final, zip_path)
    print(f"  installer: {final} ({size / 1e6:.1f} MB)")
    _ = struct, app_exe
    shutil.rmtree(work, ignore_errors=True)
    return final


if __name__ == "__main__":
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        raise SystemExit(2)
    zip_path = args[0]
    out = args[1] if len(args) > 1 else os.path.join(ROOT, "dist")
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from build_win import app_version, ver_text
    version = app_version()
    print(f"building setup for MotionForge Studio {ver_text(version)}")
    build_installer(zip_path, out, version)
