plugins {
    id 'com.android.application'
}

android {
    namespace 'com.neurio.browser'
    compileSdk 35

    defaultConfig {
        applicationId 'com.neurio.browser'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
